[features]
seeds = false
skip-lint = false

[programs.localnet]
sallar = "GKfKLJS8rnwWuKBdQtic5FC6psq44Pr7H7RPtV94fxaN"
[programs.devnet]
sallar = "GKfKLJS8rnwWuKBdQtic5FC6psq44Pr7H7RPtV94fxaN"
[programs.testnet]
sallar = "GKfKLJS8rnwWuKBdQtic5FC6psq44Pr7H7RPtV94fxaN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
